apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.containers.[name:istio-proxy].image
            value: gcr.io/mixologist-142215/proxyv2:bpy-sq-test-0512-1
          - path: spec.template.spec.containers.[name:istio-proxy].imagePullPolicy
            value: Always
  values:
    telemetry:
      v2:
        stackdriver:
          enabled: true
          outboundAccessLogging: "FULL"
          inboundAccessLogging: "FULL"
